### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Ntombi-009** [zuri-training/excel_comp_team_105#49]

**Comment by Ntombi-009** [comment]
https://www.figma.com/proto/DnC164r4V3pl8RWdOPCnFi/Github-Links?node-id=713%3A29239&scaling=scale-down&page-id=55%3A76&starting-point-node-id=713%3A29239&show-proto-sidebar=1

**Comment by Sirnzbouy** [comment]
Completed

**Comment by dwhyq** [comment]
Hi, if an issue have been resolved. Kindly close it.
